#include <stdlib.h>
#include <stdio.h>
#include <string.h>

char* handle_help(void) {
    const char* help_text = "{"
        "\"server_info\":{"
            "\"name\":\"HTTP Server v1.0\","
            "\"description\":\"High-performance HTTP/1.0 server with concurrent request processing\""
        "},"
        "\"endpoints\":{"
            "\"basic\":["
                "{\"path\":\"/status\",\"description\":\"Server status and metrics\"},"
                "{\"path\":\"/help\",\"description\":\"This help message\"},"
                "{\"path\":\"/fibonacci?num=N\",\"description\":\"Calculate Fibonacci number\"},"
                "{\"path\":\"/reverse?text=TEXT\",\"description\":\"Reverse input text\"},"
                "{\"path\":\"/toupper?text=TEXT\",\"description\":\"Convert text to uppercase\"},"
                "{\"path\":\"/random?count=N&min=A&max=B\",\"description\":\"Generate random numbers\"},"
                "{\"path\":\"/timestamp\",\"description\":\"Current server timestamp\"},"
                "{\"path\":\"/hash?text=TEXT\",\"description\":\"Calculate text hash\"},"
                "{\"path\":\"/simulate?seconds=S&task=NAME\",\"description\":\"Simulate CPU/IO workload\"},"
                "{\"path\":\"/sleep?seconds=S\",\"description\":\"Sleep for specified duration\"},"
                "{\"path\":\"/loadtest?tasks=N&sleep=X\",\"description\":\"Load testing utility\"}"
            "],"
            "\"cpu_bound\":["
                "{\"path\":\"/isprime?n=NUM\",\"description\":\"Check if number is prime\"},"
                "{\"path\":\"/factor?n=NUM\",\"description\":\"Prime factorization\"},"
                "{\"path\":\"/pi?digits=D\",\"description\":\"Calculate PI digits\"},"
                "{\"path\":\"/mandelbrot?width=W&height=H&max_iter=I\",\"description\":\"Generate Mandelbrot set\"},"
                "{\"path\":\"/matrixmul?size=N&seed=S\",\"description\":\"Matrix multiplication\"}"
            "],"
            "\"io_bound\":["
                "{\"path\":\"/sortfile?name=FILE&algo=ALGO\",\"description\":\"Sort file contents\"},"
                "{\"path\":\"/wordcount?name=FILE\",\"description\":\"Count words in file\"},"
                "{\"path\":\"/grep?name=FILE&pattern=REGEX\",\"description\":\"Search file content\"},"
                "{\"path\":\"/compress?name=FILE&codec=TYPE\",\"description\":\"Compress file\"},"
                "{\"path\":\"/hashfile?name=FILE&algo=TYPE\",\"description\":\"Calculate file hash\"}"
            "],"
            "\"files\":["
                "{\"path\":\"/createfile?name=NAME&content=TEXT&repeat=X\",\"description\":\"Create a file\"},"
                "{\"path\":\"/deletefile?name=NAME\",\"description\":\"Delete a file\"}"
            "],"
            "\"jobs\":["
                "{\"path\":\"/jobs/submit?task=TASK&params\",\"description\":\"Submit long-running job\"},"
                "{\"path\":\"/jobs/status?id=JOBID\",\"description\":\"Check job status\"},"
                "{\"path\":\"/jobs/result?id=JOBID\",\"description\":\"Get job results\"},"
                "{\"path\":\"/jobs/cancel?id=JOBID\",\"description\":\"Cancel running job\"}"
            "]"
        "},"
        "\"features\":["
            "\"Concurrent request processing\","
            "\"Job queue management\","
            "\"CPU and I/O intensive operations\","
            "\"File operations\","
            "\"Real-time metrics\""
        "]"
    "}";
    
    return strdup(help_text);
}